services:
  # Node.js backend + frontend
  - type: web
    name: exoplanet-discovery
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
    healthCheckPath: /api/health

  # Python ML API
  - type: web
    name: exoplanet-ml-api
    env: python
    buildCommand: pip install -r ml_model/requirements.txt
    startCommand: cd ml_model && python3 predict_api.py
    envVars:
      - key: PORT
        value: 5001
